### ISSUE TITLE
Clarify how the "ready" command works

### ISSUE THREAD

**Issue by bchavet** [TugboatQA/docs#139]
There are a few caveats to using a 'ready' command.

- It needs to fail gracefully before any build steps are performed
    - If the ready command depends on a script from the repo, or a running process, the initial build will fail.
- can only be one command
    - The command is specified as an array just like the other commands, but only the first command from the array is used

**Comment by dacharyc** [comment]
A Tugboat user in the Support Slack recently had more questions about the `ready` command, and suggests adding more to the documentation around this use case: https://tugboatqa.slack.com/archives/C0ZCJHW2F/p1580230833068600

**Comment by dacharyc** [comment]
From the user question above, here are the relevant notes:

>We recently merged a config change that moved the following line from the build command to the ready command, and it worked without issue:
`until nc -z localhost 3000; do sleep 1; done`

Ben had previously said to the user:

> User asks: "Is there a way to delay the preview URLs in the PR until after the app is finished starting up?"
Yes, but it can be tricky to get right. There is a "ready" command that we run when starting up a service to probe whether the service is ready or not, then sleep & repeat until it succeeds. Most of our pre-built images do a simple port check using "nc" to see if the port is open. That doesn't work well for custom node apps. 
>The trick is to get the command to pass before your app is installed, but then to wait for it to start when it is installed. We've used something like this on one of our recent projects, where the logic for whether the app is ready once installed is handled inside of that script:
`test ! -x $TUGBOAT_ROOT/.tugboat/node-ready.sh || $TUGBOAT_ROOT/.tugboat/node-ready.sh`

- Code above is basically saying “If the node-ready.sh script isn’t present yet, return “success”. If it is available, execute it.”

Relevant notes from further conversation include:
- `ready` command must pass before the app is installed because Tugboat needs to spin up the service prior to the app being installed. So if `ready` command depends on app being installed, Tugboat would be stuck.

> it may help to consider the original purpose of the `ready` command, which was that commands for php services were running before mysql had finished starting up, so builds were failing with “unable to connect to mysql”
> the `ready` command for the mysql service in that case, is “is mysql up and accepting connections?” If not, wait a second and check again

The user in this case suggested building out more documentation for the `ready` command at: https://docs.tugboat.qa/building-a-preview/preview-deep-dive/how-previews-work/#the-build-process-explained

**Comment by dacharyc** [comment]
New but similar issue around `ready` with a node app:

User notes: "sometimes when a preview resumes it momentarily shows an error page. Sometimes it corrects by refreshing on its own, other times the user has to manually refresh the page."

- It's a side-effect of running a node app, and Tugboat trying to figure out when the preview is "ready"
- Container starts, app is still loading, but nothing is listening yet, so proxy throws a 502 (or 503?)
- When you build without a Base Preview using the `ready` command to address this, the command is checked on the very first time the containers start. Your app isn't installed yet, so the container will never be `ready` - it will get stuck. Something like: 
`ready: "! test -f ${TUGBOAT_ROOT}/.tugboat/config.yml  || sleep 20"` gives extra time for a node app to start up.

Maybe add to Starter Configs -> Code Snippets an example of `ready` in something like `.tugboat/node-ready.sh`:
`#!/bin/sh
set -eu
curl \
  --silent \
  --retry 50 \
  --retry-delay 1 \
  --retry-connrefused \
  --max-time 4 \
  --retry-max-time 240 \
  localhost:3000 > /dev/null || true`

- The above tries to make a request to localhost on port 3000 until there's a response

Then add to the `config.yml`:
`      ready:
        - 'test ! -x $TUGBOAT_ROOT/.tugboat/node-ready.sh || $TUGBOAT_ROOT/.tugboat/node-ready.sh'`

- That makes sure the `ready` command passes if the `node-ready.sh` script isn't available yet, and if it _is_ available, will execute it to see if the node app is running

**Comment by dacharyc** [comment]
- Add to documentation around `ready` as a top level item under Setting up Services -> How to Set up Services. Similar to: https://docs.tugboat.qa/setting-up-services/how-to-set-up-services/running-a-background-process/

- Add a `ready` section to Troubleshooting -> Preview Won't Build -> My Preview is stuck at: https://docs.tugboat.qa/troubleshooting/preview-wont-build/#my-preview-build-is-stuck-at

- Consider adding something to How Previews Work -> The Build Process: Explained: https://docs.tugboat.qa/building-a-preview/preview-deep-dive/how-previews-work/#the-build-process-explained
